on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        type: choice
        options:
          - "Staging"
          - "Production"
      run_ui_tests:
        description: 'Run UI testing'
        required: true
        type: boolean
        default: false
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ steps.set-status.outputs.status }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v7.0.0
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref_name }}
      - name: List files in workspaces
        run: ls ${{ github.workspace }}
      - name: Set an output status
        id: set-status
        run: |
          echo "Get result from building process"
          echo "status-success" >> $GITHUB_OUTPUT
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: UI Testing
        if: ${{ inputs.run_ui_tests }}
        run: |
          echo "The build status is ${{ needs.build.outputs.build_status }}"
          echo "Run UI testing tools in ${{ inputs.environment }} environment"

name: Container Workflow
on: workflow_dispatch

env:
  ACR_LOGIN_SERVER: aistraining.azurecr.io
  TAG_NAME: eshoponweb-013:1.0.0
  IMAGE_NAME: ${{ vars.ACR_LOGIN_SERVER }}/${{ vars.TAG_NAME }}
  
jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0

      - name: ACR Login
        uses: azure/docker-login@v1
        with:
          login-vserver: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker build -f src/Web/Dockerfile -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.TAG_NAME }} .
          docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.TAG_NAME }}
