name: Test Runner
on: workflow_dispatch
jobs:
  test-runner:
    runs-on: 
      - self-hosted
      - docker
      - javascript
      - ubuntu-latest
    
    steps:
      - run: echo "Test echo in first github runner"
      - name: Checkout
        uses: action/checkout@v7.0.0
